// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjurUXNmsfqY0LxBHQ3rSU7rtBqMx3ASw',
    appId: '1:1041880438023:web:8342db5f582d0efd4861a2',
    messagingSenderId: '1041880438023',
    projectId: 'flutter-firebase-app-e6fb9',
    authDomain: 'flutter-firebase-app-e6fb9.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-app-e6fb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-app-e6fb9.appspot.com',
    measurementId: 'G-EN3Z41SNHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUGa9-LuXTEzhhm9zNcbDEwUla9LHJA4',
    appId: '1:1041880438023:android:b8de00a5856e4ecb4861a2',
    messagingSenderId: '1041880438023',
    projectId: 'flutter-firebase-app-e6fb9',
    databaseURL: 'https://flutter-firebase-app-e6fb9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-firebase-app-e6fb9.appspot.com',
  );
}
